/**
 * PDF Export Utility for StudyPlan
 * Generates a clean, well-formatted PDF of the user's study plan
 * using jsPDF (loaded via CDN in index.html).
 */

/**
 * Export the current study plan as a downloadable PDF.
 * @param {Array} tasks  - Array of task objects from the store
 * @param {Array} subjects - Array of subject objects from the store
 */
export function exportStudyPlanAsPDF(tasks, subjects) {
  if (!window.jspdf || !window.jspdf.jsPDF) {
    alert('PDF library is still loading. Please wait a moment and try again.');
    return;
  }

  try {
  const { jsPDF } = window.jspdf;

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 18;
  const marginRight = 18;
  const contentWidth = pageWidth - marginLeft - marginRight;
  let y = 0;

  // ─── Color palette (RGB arrays) ───
  const colors = {
    primary:    [26, 26, 24],
    secondary:  [107, 107, 102],
    tertiary:   [156, 154, 146],
    accent:     [79, 70, 229],
    success:    [22, 101, 52],
    danger:     [163, 45, 45],
    warning:    [133, 79, 11],
    info:       [24, 95, 165],
    white:      [255, 255, 255],
    lightGray:  [247, 247, 245],
    border:     [230, 230, 225],
  };

  // ─── Helpers ───
  function setColor(c) { doc.setTextColor(c[0], c[1], c[2]); }
  function setDrawColor(c) { doc.setDrawColor(c[0], c[1], c[2]); }
  function setFillColor(c) { doc.setFillColor(c[0], c[1], c[2]); }

  function checkPageBreak(neededHeight) {
    if (y + neededHeight > pageHeight - 20) {
      // Footer on current page before breaking
      drawPageFooter();
      doc.addPage();
      y = 20;
    }
  }

  function drawPageFooter() {
    const pageNum = doc.internal.getCurrentPageInfo().pageNumber;
    doc.setFontSize(9);
    setColor(colors.tertiary);
    doc.text(`Page ${pageNum}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text('Generated by StudyPlan', marginLeft, pageHeight - 10);
    const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
    doc.text(dateStr, pageWidth - marginRight, pageHeight - 10, { align: 'right' });
  }

  function formatDate(dateStr) {
    if (!dateStr) return 'No deadline';
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  }

  // ─── Header / Title Section ───
  // Accent bar at top
  setFillColor(colors.accent);
  doc.rect(0, 0, pageWidth, 3, 'F');

  y = 22;
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  setColor(colors.primary);
  doc.text('StudyPlan', marginLeft, y);

  y += 8;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  setColor(colors.secondary);
  const exportDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });
  doc.text(`Exported on ${exportDate}`, marginLeft, y);

  // Horizontal divider
  y += 6;
  setDrawColor(colors.border);
  doc.setLineWidth(0.5);
  doc.line(marginLeft, y, pageWidth - marginRight, y);
  y += 10;

  // ─── Summary Stats ───
  const activeTasks = tasks.filter(t => !t.archived);
  const completedTasks = activeTasks.filter(t => t.status === 'Done');
  const pendingTasks = activeTasks.filter(t => t.status !== 'Done');
  const overdueTasks = pendingTasks.filter(t => {
    if (!t.due_at) return false;
    return new Date(t.due_at) < new Date();
  });

  // Stat cards
  const statBoxW = (contentWidth - 12) / 4;  // 4 boxes with 4px gaps
  const statBoxH = 22;
  const stats = [
    { label: 'Total Tasks',  value: String(activeTasks.length),    color: colors.info },
    { label: 'Completed',    value: String(completedTasks.length), color: colors.success },
    { label: 'Pending',      value: String(pendingTasks.length),   color: colors.warning },
    { label: 'Overdue',      value: String(overdueTasks.length),   color: colors.danger },
  ];

  stats.forEach((stat, i) => {
    const x = marginLeft + i * (statBoxW + 4);
    // Background
    setFillColor(colors.lightGray);
    doc.roundedRect(x, y, statBoxW, statBoxH, 3, 3, 'F');
    // Colored left accent
    setFillColor(stat.color);
    doc.rect(x, y + 3, 2, statBoxH - 6, 'F');
    // Value
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    setColor(stat.color);
    doc.text(stat.value, x + 8, y + 10);
    // Label
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    setColor(colors.tertiary);
    doc.text(stat.label, x + 8, y + 17);
  });

  y += statBoxH + 12;

  // ─── Progress bar ───
  const progress = activeTasks.length > 0
    ? Math.round((completedTasks.length / activeTasks.length) * 100)
    : 0;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  setColor(colors.primary);
  doc.text(`Overall Progress: ${progress}%`, marginLeft, y);
  y += 5;

  // Bar background
  const barH = 5;
  setFillColor(colors.border);
  doc.roundedRect(marginLeft, y, contentWidth, barH, 2, 2, 'F');
  // Bar fill
  if (progress > 0) {
    const fillWidth = (progress / 100) * contentWidth;
    setFillColor(colors.success);
    doc.roundedRect(marginLeft, y, fillWidth, barH, 2, 2, 'F');
  }
  y += barH + 14;

  // ─── Subject-wise Sections ───
  // Group tasks by subject
  const subjectMap = {};
  subjects.forEach(s => { subjectMap[s.id] = { ...s, tasks: [] }; });

  // Catch tasks with no matching subject
  const generalSubject = { id: '_general', name: 'General', color: '', tasks: [] };

  activeTasks.forEach(t => {
    if (subjectMap[t.subject_id]) {
      subjectMap[t.subject_id].tasks.push(t);
    } else {
      generalSubject.tasks.push(t);
    }
  });

  const subjectsToRender = Object.values(subjectMap)
    .filter(s => s.tasks.length > 0)
    .sort((a, b) => a.name.localeCompare(b.name));

  if (generalSubject.tasks.length > 0) {
    subjectsToRender.push(generalSubject);
  }

  // Subject color map → RGB
  function subjectColorToRGB(colorStr) {
    if (!colorStr) return colors.info;
    if (colorStr.includes('info'))    return colors.info;
    if (colorStr.includes('success')) return colors.success;
    if (colorStr.includes('purple'))  return [60, 52, 137];
    if (colorStr.includes('warning')) return colors.warning;
    if (colorStr.includes('danger'))  return colors.danger;
    return colors.info;
  }

  subjectsToRender.forEach(subject => {
    const subColor = subjectColorToRGB(subject.color);

    // Check page break for at least the header + one task row
    checkPageBreak(30);

    // Subject header
    setFillColor(subColor);
    doc.roundedRect(marginLeft, y, contentWidth, 10, 2, 2, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    setColor(colors.white);
    doc.text(subject.name.toUpperCase(), marginLeft + 6, y + 7);

    // Subject task count
    const subDone = subject.tasks.filter(t => t.status === 'Done').length;
    const subTotal = subject.tasks.length;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`${subDone}/${subTotal} completed`, pageWidth - marginRight - 6, y + 7, { align: 'right' });

    y += 14;

    // Table header
    checkPageBreak(12);
    setFillColor(colors.lightGray);
    doc.rect(marginLeft, y, contentWidth, 8, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    setColor(colors.tertiary);

    const colStatus = marginLeft + 4;
    const colTask = marginLeft + 22;
    const colDeadline = marginLeft + contentWidth * 0.55;
    const colNotes = marginLeft + contentWidth * 0.78;

    doc.text('STATUS', colStatus, y + 5.5);
    doc.text('TASK', colTask, y + 5.5);
    doc.text('DEADLINE', colDeadline, y + 5.5);
    doc.text('NOTES', colNotes, y + 5.5);
    y += 10;

    // Sort tasks: pending first (sorted by due_at), then completed
    const sortedTasks = [...subject.tasks].sort((a, b) => {
      if (a.status === 'Done' && b.status !== 'Done') return 1;
      if (a.status !== 'Done' && b.status === 'Done') return -1;
      return new Date(a.due_at || '9999') - new Date(b.due_at || '9999');
    });

    sortedTasks.forEach((task, idx) => {
      checkPageBreak(14);

      const isDone = task.status === 'Done';
      const isOverdue = !isDone && task.due_at && new Date(task.due_at) < new Date();
      const rowH = 10;

      // Alternating row background
      if (idx % 2 === 0) {
        setFillColor([252, 252, 250]);
        doc.rect(marginLeft, y, contentWidth, rowH, 'F');
      }

      // Status indicator (checkbox-style)
      if (isDone) {
        setFillColor(colors.success);
        doc.roundedRect(colStatus, y + 2.5, 5, 5, 1.2, 1.2, 'F');
        // Checkmark
        doc.setLineWidth(0.6);
        setDrawColor(colors.white);
        doc.line(colStatus + 1, y + 5, colStatus + 2.2, y + 6.5);
        doc.line(colStatus + 2.2, y + 6.5, colStatus + 4, y + 3.8);
      } else {
        doc.setLineWidth(0.5);
        setDrawColor(isOverdue ? colors.danger : colors.border);
        doc.roundedRect(colStatus, y + 2.5, 5, 5, 1.2, 1.2, 'S');
      }

      // Task title
      doc.setFontSize(9);
      doc.setFont('helvetica', isDone ? 'normal' : 'bold');
      setColor(isDone ? colors.tertiary : colors.primary);
      const titleText = doc.splitTextToSize(task.title || 'Untitled', contentWidth * 0.32);
      doc.text(titleText[0], colTask, y + 6.5);

      // Deadline
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      setColor(isOverdue ? colors.danger : colors.secondary);
      doc.text(formatDate(task.due_at), colDeadline, y + 6.5);

      // Notes (truncated)
      setColor(colors.tertiary);
      const notesText = task.notes ? (task.notes.length > 25 ? task.notes.substring(0, 22) + '...' : task.notes) : '—';
      doc.text(notesText, colNotes, y + 6.5);

      y += rowH + 1;
    });

    // Bottom border for section
    setDrawColor(colors.border);
    doc.setLineWidth(0.3);
    doc.line(marginLeft, y, pageWidth - marginRight, y);
    y += 10;
  });

  // ─── Empty state ───
  if (subjectsToRender.length === 0) {
    checkPageBreak(20);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'normal');
    setColor(colors.secondary);
    doc.text('No tasks found. Add tasks to your study plan to see them here.', pageWidth / 2, y, { align: 'center' });
    y += 20;
  }

  // ─── Final footer on last page ───
  drawPageFooter();

  // ─── Download ───
  const fileName = `StudyPlan_${new Date().toISOString().slice(0, 10)}.pdf`;
  const pdfBlob = doc.output('blob');
  const blobUrl = URL.createObjectURL(new Blob([pdfBlob], { type: 'application/pdf' }));
  const link = document.createElement('a');
  link.href = blobUrl;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(blobUrl), 100);

  } catch (err) {
    console.error('PDF Export Error:', err);
    alert('Failed to generate PDF. Please try again.');
  }
}
